# ModelArguments
model_name_or_path: meta-llama/Llama-3.2-11B-Vision-Instruct
use_4bit_quantization: false
lora_r: 32
lora_alpha: 128
lora_dropout: 0.05
target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj


# DataArguments
data_file: ./data/hpo/qa_with_chat_template_250201.csv
split_ratio: 0.1
max_seq_length: 500


# TrainingArguments
run_name: TOMMI-0.2
report_to:
- wandb
seed: 42
bf16: true
num_train_epochs: 10
per_device_train_batch_size: 18
per_device_eval_batch_size: 8
gradient_checkpointing: true
gradient_accumulation_steps: 2
learning_rate: 1e-3
warmup_steps: 100
weight_decay: 0.01
save_strategy: steps
save_steps: 100
save_total_limit: 10
logging_strategy: steps
log_level: info
logging_steps: 1
overwrite_output_dir: true